AWSTemplateFormatVersion: "2010-09-09"
Description: IAM IdC AWS Accout management database template

Parameters:
  TableNamePrefix:
    Type: String
  CategoryName:
    Description: "Resource category name"
    Type: String
    Default: "iam-idc"
  DynamoDBDeletionPolicy:
    Description: "Deletion policy for the DynamoDB table"
    Type: String
    Default: Retain
    AllowedValues:
      - Delete
      - Retain

Resources:
  IamIdcAwsAccountManagementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join
        - "-"
        - - !Ref TableNamePrefix
          - !Ref CategoryName
          - "AwsAccountManagement"
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: accountId
          AttributeType: S
      KeySchema:
        - AttributeName: accountId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
    DeletionPolicy: !Ref DynamoDBDeletionPolicy
  IamIdcPermissionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join
        - "-"
        - - !Ref TableNamePrefix
          - !Ref CategoryName
          - "Permission"
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: permissionId
          AttributeType: S
        - AttributeName: awsAccountId
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: permissionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: awsAccountId_name_index
          KeySchema:
            - AttributeName: awsAccountId
              KeyType: HASH
            - AttributeName: name
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
    DeletionPolicy: !Ref DynamoDBDeletionPolicy
